version: "3.3"

services:
  api:
    build: .
    ports: 
      - 8000:80
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres

