version: "3.3"

services:
  api:
    build: .
    ports: 
      - 8000:80
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres

